### ISSUE TITLE
Development roadmap

### ISSUE THREAD

**Issue by sshin23** [mit-shin-group/BlockStructuredSolvers#1]
Here's the development roadmap. In the short term, we should focus on:
- [x] Performance optimization: we should ensure that `factorize!` and `solve!` doesn't allocate memory
- [x] GPU implementation: we should make sure that we can formulate/solve problems on GPUs using the relevant BLAS/LAPACK routines in CUDA.jl
- [x] Batched parallelism 
- [x] Nested partitioning

In the long term we should consider several generalizations/specializations:
- [x] Portability: run on non-NVIDIA GPUs
- [ ] Specialization for dynamic programs
- [ ] Generalization for HODLR matrices
- [ ] Block multi-diagonal systems

Also, we should think of a cool name. We should convey a message that this solver targets structured sparse-dense systems
